Dre 42
harlequin-plus/dreamteam_mf05 pull request #12
Opened 2024-03-25 11:00 UTC by palhair

### Добавляет Redux-хранилище. добавлен слайс для юзера

2024-03-26 18:35 UTC, mixamax commented on packages/client/src/components/SignUpForm/index.tsx
> +      dispatch(fetchUser())
может, ошибаюсь, но я только учусь))
тут два раза в signUp(user) и dispatch(fetchUser()) идет запрос getUser, если я правильно понимаю, может, устанавливать юзера в стор сразу в сервисе signUp через store.dispatch()? или сервис переделаем?

2024-03-27 09:07 UTC, harlequin-plus approved these changes
State обнуляется при перезагрузке страницы

2024-03-27 14:17 UTC, palhair commented
Насколько я понимаю редакс по сути объект состояния js. Он не хранится локально и при перезагрузке создается заново. 
И надо добавлять юзера также заново. По идее после логики авторизации можно добавить юзера в стате, чтобы 2 раза не делать запрос. Но авторизации с перенаправлением пока нет.

2024-03-27 19:27 UTC, IvanPeleshok requested changes
Прекрасно поработали, нравится

Есть небольшие замечания, предлагаю доработать

Хорошего дня :)

2024-03-27 19:27 UTC, IvanPeleshok commented on packages/client/src/app/Router.tsx
> +  //   if (isLoading) return <div>...loading</div>
Если не используется, то предлагаю удалить, либо добавить осмысленный комментарий

2024-03-27 19:27 UTC, IvanPeleshok commented on packages/client/src/components/LoginForm/index.tsx
> +    await signIn(user) //запрос на вход
Предлагаю обработать возврат исключения из промисса, если этого ещё не было реализовано с помощью try / catch на любом уровне

2024-03-27 19:27 UTC, IvanPeleshok commented on packages/client/src/pages/Profile.tsx
> +  console.log(user)
Нужен ли отладочный код?

2024-03-27 19:27 UTC, IvanPeleshok commented on packages/client/src/pages/Profile.tsx
> +  const user = userState.item ? userState.item : defaultUser
Ваш слайсл может возвращать значение по-умолчанию
Для чего данное условие на этом уровне?

2024-03-27 19:27 UTC, IvanPeleshok commented on packages/client/src/store/index.ts
> +    userState: userReducer,
Предлгаю назвать слайс user (мы и так понимаем, что это state)

2024-03-27 19:27 UTC, IvanPeleshok commented on packages/client/src/store/userState.ts
> +type LoadStatus = 'success' | 'loading' | 'failed' | 'noloaded'
Есть смысл вынести в более глобальный скоуп, чтобы в других модулях можно было воспользоваться данным типом

2024-03-27 19:27 UTC, IvanPeleshok commented on packages/client/src/store/userState.ts
> +type Nullable<T> = T | null
Аналогично

2024-03-27 19:27 UTC, IvanPeleshok commented on packages/client/src/store/userState.ts
> +export const fetchUser = () => async (dispatch: AppDispath) => {
Для асинхронной логики предлагаю воспользоваться следующей фичой из redux-toolkit

https://redux-toolkit.js.org/api/createAsyncThunk
Пример:
https://redux-toolkit.js.org/api/createAsyncThunk#handling-thunk-errors
```
const updateUser = createAsyncThunk(
  'users/update',
  async (userData, { rejectWithValue }) => {
    const { id, ...fields } = userData
    try {
      const response = await userAPI.updateById(id, fields)
      return response.data.user
    } catch (err) {
      // Use `err.response.data` as `action.payload` for a `rejected` action,
      // by explicitly returning it using the `rejectWithValue()` utility
      return rejectWithValue(err.response.data)
    }
  },
)

2024-03-28 18:36 UTC, IvanPeleshok requested changes
Добрый день!

Есть небольшое замечания, предлагаю поправить

Хорошего дня :)

2024-03-28 18:36 UTC, IvanPeleshok commented on packages/client/src/store/userState.ts
> +export const fetchUser = createAsyncThunk('userState/fetchStatus', async () => {
Предлагаю обработать исключение, которое может вернуть промисс
Пример обработки в createAsyncThunk ниже:
https://redux-toolkit.js.org/api/createAsyncThunk#handling-thunk-errors
```
const updateUser = createAsyncThunk(
  'users/update',
  async (userData, { rejectWithValue }) => {
    const { id, ...fields } = userData
    try {
      const response = await userAPI.updateById(id, fields)
      return response.data.user
    } catch (err) {
      // Use `err.response.data` as `action.payload` for a `rejected` action,
      // by explicitly returning it using the `rejectWithValue()` utility
      return rejectWithValue(err.response.data)
    }
  },
)

2024-03-29 15:06 UTC, IvanPeleshok approved these changes
Отличная работа

Поздравляю, апрув

Хорошего дня :)

2024-03-29 15:26 UTC, merged