Fullscreen mode was added.
harlequin-plus/dreamteam_mf05 pull request #13
Opened 2024-03-25 18:21 UTC by zhel1

Добавить одно из описанных в уроках Web API: - Fullscreen API, - Geolocation API, - Perfomance API, - Notification API.

![Анимация](https://github.com/harlequin-plus/dreamteam_mf05/assets/30962820/afa4817d-1f10-43fa-a683-752cfd785fee)

2024-03-26 19:45 UTC, Geegtor approved these changes

2024-03-28 09:51 UTC, kate-lozovaya requested changes
Оставила комментарии. Посмотри их, пожалуйста, и призывай меня к ревью

2024-03-28 09:51 UTC, kate-lozovaya commented on packages/client/src/components/FullscreenProvider/index.tsx
> +  (ms[0] in document && ms) ||
[Предложение]
Выглядит не очень надежно. Кто-то может случайно поменять порядок элементов в массивах, и тогда все сломается. Может их в объекты преобразовать, чтобы здесь брать значение по ключу? 
Ну или хотя бы комментарий оставить, что порядок менять нельзя

2024-03-28 09:51 UTC, kate-lozovaya commented on packages/client/src/components/FullscreenProvider/index.tsx
> +class fscreen {
[Исправление]
В этом файле как-то все смешано. Предлагаю разделить и сделать два файла - для класса и для компонента. Константы тоже можно перенести в отдельный файл, но тут это не выглядит обязательным, сделай на свое усмотрение.
Если в проекте используется `index.ts` для определения экспортов, то в нем нужно оставить только экспорт компонента

2024-03-28 09:51 UTC, kate-lozovaya commented on packages/client/src/components/FullscreenProvider/index.tsx
> +    // eslint-disable-line
[Предложение]
Не нравится, что тут все строки получаются задизейбленными. Посмотри, может получится избавиться от `any` и прописать правильные типы

2024-03-28 09:51 UTC, kate-lozovaya commented on packages/client/src/components/FullscreenProvider/index.tsx
> +  onOpen?: () => void
[Предложение]
Мне нравится записывать типы вот так:
```suggestion
  onChange?(state: boolean): void
  onClose?(): void
  onOpen?(): void
```
Они в таком случае подсвечиваются в иде другим цветом и сразу видно, что переменная, а что - функция.
Это просто то, что мне нравится, ты можешь писать, как удобно

2024-03-28 09:51 UTC, kate-lozovaya commented on packages/client/src/components/FullscreenProvider/index.tsx
> +    }
[Предложение]
Здесь можно избавиться от условия и поставить `?.` к функции
```suggestion
    onChange?.(!!fscreen.fullscreenElement)
```

2024-03-28 09:51 UTC, kate-lozovaya commented on packages/client/src/components/FullscreenProvider/index.tsx
> +    }
[Предложение]
Здесь можно избавиться от `onOpen` в условии

2024-03-28 09:51 UTC, kate-lozovaya commented on packages/client/src/components/FullscreenProvider/index.tsx
> +    if (onClose && !fscreen.fullscreenElement) {
[Предложение]
Здесь можно избавиться от `onClose` в условии

2024-03-28 09:51 UTC, kate-lozovaya commented on packages/client/src/components/FullscreenProvider/index.tsx
> +  const handleChange = () => {
[Исправление]
Оберни функцию в `useCallback`

2024-03-28 09:51 UTC, kate-lozovaya commented on packages/client/src/components/FullscreenProvider/index.tsx
> +      onClose()
[Предложение]
Выполнение `onOpen` и `onClose` взаимоисключающие, чтобы это показать и чуть сократить код, можно записать их в тернарном операторе 
`!!fscreen.fullscreenElement ? onOpen?.() : onClose?.()`

2024-03-28 09:51 UTC, kate-lozovaya commented on packages/client/src/components/FullscreenProvider/index.tsx
> +  }, [])
[Вопрос]
А в зависимостях не нужен `handleChange`?
Проверь, есть ли в линтере правило `react-hooks/exhaustive-deps`, которое показывает варнинги, если не указаны зависимости для хуков

2024-03-28 09:51 UTC, kate-lozovaya commented on packages/client/src/components/FullscreenProvider/index.tsx
> +      style={{ height: '100%', width: '100%' }}>
[Вопрос]
Не получится перенести `{ height: '100%', width: '100%' }` в класс?

2024-03-28 09:51 UTC, kate-lozovaya commented on packages/client/src/components/GameBoard/GameBoard.tsx
> +      }>
[Исправление]
Интерфейс `onChange` и `setFullscreenEnabled` совпадает, можно сразу показать, что параметр - функция
```suggestion
      onChange={setFullscreenEnabled}
      >
```

2024-03-28 09:51 UTC, kate-lozovaya commented on packages/client/src/components/GameBoard/GameBoard.tsx
> +          onClick={() => setFullscreenEnabled(!isFullscreenEnabled)}
[Исправление]
Для изменения состояния правильнее использовать параметр сета `setFullscreenEnabled`, а не само текущее значение `isFullscreenEnabled`. [Вот тут](https://stackoverflow.com/questions/59073180/react-usestate-using-previous-state-vs-not-using-previous-state) на стековерфлоу есть примеры, что именно будет не так.
```suggestion
          onClick={() => setFullscreenEnabled(prev => !prev)}
```

2024-03-28 21:54 UTC, zhel1 commented on packages/client/src/components/FullscreenProvider/index.tsx
> +    // eslint-disable-line
Пытался, не вышло :(

2024-03-29 07:42 UTC, kate-lozovaya approved these changes
Непонятно, почему появились дизейблы для правила с зависимостями хуков. Лучше не дизейблить, а поставить зависимости, ну либо подписать комментарий, почему они не нужны, что из-за этого сломается.

В остальном все ок, поэтому поставлю апрув. Но с дизейблами разберись, пожалуйста )

2024-03-29 07:42 UTC, kate-lozovaya commented on packages/client/src/components/Form/index.tsx
>      refs[input.name] = useRef() as React.MutableRefObject<InputRef>
[Вопрос]
А почему тут пришлось сделать дизейбл?

2024-03-29 07:42 UTC, kate-lozovaya commented on packages/client/src/components/GameBoard/GameBoard.tsx
> +  }, []) // eslint-disable-line
[Вопрос]
Зачем тут дизейбл правила? Может просто добавить нужную зависимость?

2024-03-29 16:44 UTC, merged