DRE-21 лендинг с презентацией игры. Хедер, футер, мобильное меню.
harlequin-plus/dreamteam_mf05 pull request #18
Opened 2024-03-31 17:53 UTC by harlequin-plus

Верстка и анимация лендинга для презентации игры. Добавлены хедер и футер на весь сайт. Сделано мобильное меню - бургер.
Для анимации лендинга использовался gsap. 

Видео демо - 
[screen-capture (8).webm](https://github.com/harlequin-plus/dreamteam_mf05/assets/27853495/290e23d3-7764-49d3-95bb-87b2988c7ef4)

2024-03-31 18:35 UTC, palhair approved these changes

2024-03-31 18:43 UTC, IvanPeleshok requested changes
Отличная работа, классно придумали

Ни разу ещё не видел подобной реализации лендинга с презентацией игры

Есть небольшая просьба с отступами в правилах css, чтобы улучшить читаемость модулей

Предлагаю поправить

В остальном прекрасная работа

Хорошего дня :)

2024-03-31 18:43 UTC, IvanPeleshok commented on packages/client/src/assets/styles/App.scss
> +  @media(min-width:1280px) {
Было бы здорово оставлять пустые пробелы внутри правил, чтобы это было проще читать

2024-03-31 18:43 UTC, IvanPeleshok commented on packages/client/src/components/Footer/style.scss
> +  &__menu {
Было бы здорово оставлять пустые пробелы внутри правил, чтобы это было проще читать

Предлагаю поправить во всём PR отступы в файлах с правилам

2024-03-31 18:43 UTC, IvanPeleshok commented on packages/client/src/components/Header/HeaderMenu/index.tsx
> +        aria-controls={open ? 'basic-menu' : undefined}
```
open && 'basic-menu'
```
Ниже соответсвенно

2024-03-31 18:43 UTC, IvanPeleshok commented on packages/client/src/components/Header/style.scss
> +  box-shadow: 0 4px 4px 0 rgba(0, 0, 0, 0.1);
Можно вынести цвет в перменную

2024-03-31 18:43 UTC, IvanPeleshok commented on packages/client/src/pages/partical/MainPage/Rectangles/style.scss
> +      background-color: #1D1F34;
Цвета можно вынести в переменные

2024-03-31 19:13 UTC, harlequin-plus commented on packages/client/src/components/Header/HeaderMenu/index.tsx
> +        aria-controls={open ? 'basic-menu' : undefined}
Не совсем понял, зачем нужно в условие добавлять строку 'basic-menu'?

2024-03-31 19:40 UTC, palhair commented on packages/client/src/components/Header/HeaderMenu/index.tsx
> +        aria-controls={open ? 'basic-menu' : undefined}
https://learn.javascript.ru/nullish-operators#operator-nulevogo-sliyaniya

2024-04-01 06:31 UTC, IvanPeleshok commented on packages/client/src/components/Header/HeaderMenu/index.tsx
> +        aria-controls={open ? 'basic-menu' : undefined}
```
true && 'value' === value
false && 'value' === false
```
Если необходимо передать undefined, open === false, то ваше решение валидное

Просто предложил сократить запись

2024-04-01 06:32 UTC, IvanPeleshok approved these changes
Всё замечательно, отличная реализация
Работа принята

Хорошего дня :)

2024-04-01 07:53 UTC, merged