DRE-49: API for leaderboard was added.
harlequin-plus/dreamteam_mf05 pull request #33
Opened 2024-04-23 21:37 UTC by zhel1

### DRE-49 Добавить API для лидерборда.

![Анимация](https://github.com/harlequin-plus/dreamteam_mf05/assets/30962820/ed59e44b-b520-4a04-acc0-da5d97c8ed5b))

2024-04-24 08:22 UTC, palhair approved these changes

2024-04-24 08:22 UTC, palhair commented on packages/client/src/models/TUser.ts
> -  display_name: string | null
Почему поменял? апи яндекса возвращает null

2024-04-24 17:48 UTC, zhel1 commented on packages/client/src/models/TUser.ts
> -  display_name: string | null
Экспериментировал с типами и забыл вернуть) Исправил, спасибо)

2024-04-25 08:27 UTC, kate-lozovaya requested changes
Написала несколько вопросов и предложений с исправлениями. Отвечай на них и призывай меня к ревью. 

Постарайся поаккуратнее прописать типы для функций лидерборда, чтобы не нужно было использовать `any` и `as`, они просто выключают `typescript` и все его плюсы

2024-04-25 08:27 UTC, kate-lozovaya commented on packages/client/server/repository/SsrYandexAPILeaderboardRepository.ts
> +  async getCurrentLeaderboard(): Promise<any> {
[Вопрос-Исправление]
Тут неизвестен тип? Может получится избавиться от `any`?

2024-04-25 08:27 UTC, kate-lozovaya commented on packages/client/server/repository/SsrYandexAPILeaderboardRepository.ts
> +  async getCurrentLeaderboard(): Promise<any> {
any - плохая практика, просто выключается typescript

2024-04-25 08:27 UTC, kate-lozovaya commented on packages/client/server/repository/SsrYandexAPILeaderboardRepository.ts
> +    const list = data as Array<object>
[Предложение]
Если избавиться от any выше, то тут не нужен будет `as Array<object>`.
Если с данными что-то случится и тип поменяется, типы не будут показывать ошибку из-за `as`

И по названию list непонятно, список чего здесь. Лучше отобразить смысл в названии

2024-04-25 08:27 UTC, kate-lozovaya commented on packages/client/server/repository/SsrYandexAPILeaderboardRepository.ts
> +    const detailedList: Array<object> = []
[Исправление]
Здесь ведь заранее понятно ,какие поля есть в объекте. Может прописать их тут?

2024-04-25 08:27 UTC, kate-lozovaya commented on packages/client/server/repository/SsrYandexAPILeaderboardRepository.ts
> +      list.map(async (leader: { data }) => {
[Исправление]
[map используется для преобразования значений](https://learnjs.ru/lessons/array-map/) исходного массива, а не для создания цикла. Тут в `map` ничего не возвращается, он не нужен. 
И `Promise.all` тут не нужен. Запрос обернут в `try catch`, можно показывать ошибку по попаданию в `catch`.

Предлагаю тут использовать обычный цикл for
```
for (const leader of list) {
...
```

2024-04-25 08:27 UTC, kate-lozovaya commented on packages/client/src/services/user.ts
> +  return response.data as TUser
[Вопрос]
Зачем тут `as TUser`? В `await userApi.changeAvatar(formData)` есть тип

2024-04-25 08:27 UTC, kate-lozovaya commented on packages/client/src/components/Leaderboard/index.tsx
> +      event: React.MouseEvent<HTMLButtonElement> | null,
[Вопрос-Исправление]
А зачем `event`, он же не используется?

2024-04-25 08:27 UTC, kate-lozovaya commented on packages/client/src/components/Leaderboard/index.tsx
> +          count={Math.min(allLeaders ? allLeaders.length : 0)}
[Вопрос-Исправление]
Зачем `Math.min` для одного значения?
И можно упростить запись в [скобках с оператором `??`](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing) - ` allLeaders?.length ?? 0`

2024-04-25 08:27 UTC, kate-lozovaya commented on packages/client/src/components/Leaderboard/index.tsx
> +            allLeaders ? allLeaders.length : 0,
[Предложение]
Можно сократить ка ки выше
```suggestion
            allLeaders?.length ?? 0,
```

2024-04-25 08:27 UTC, kate-lozovaya commented on packages/client/src/services/leaderboard.ts
> +  const list = response.data as TLeaderboardData
[Вопрос-Исправление]
Тут точно нужен `as TLeaderboardData`? `await leaderboardApi.getLeaderboard(data)` не возвращает тип?

2024-04-25 08:27 UTC, kate-lozovaya commented on packages/client/src/store/leaderboardState.ts
> +  items: TLeaderboardData | undefined
[Вопрос]
Тут хочется показать, что `items` - обязательное поле, которое будет всегда? Или почему-то еще не использовалась запись `items?: TLeaderboardData`? Обычно для `undefined` используются опциональные поля с `?`

2024-04-25 08:30 UTC, kate-lozovaya requested changes

2024-04-25 08:30 UTC, kate-lozovaya commented on packages/client/src/components/Leaderboard/index.tsx
> +  const displayedLeaders = allLeaders?.slice(
[Исправление]
Тут лучше обернуть в `useMemo`, что бы перерендер списка был только при изменении `allLeaders` и `page`

2024-04-25 18:55 UTC, zhel1 commented on packages/client/src/components/Leaderboard/index.tsx
> +      event: React.MouseEvent<HTMLButtonElement> | null,
Параметр event есть в сигнатуре метода onPageChange компонента TablePagination из библиотеки mui. Он стоит первым, а мне нужен второй параметр, поэтому пришлось указать

2024-04-25 19:37 UTC, zhel1 commented on packages/client/src/services/leaderboard.ts
> +  const list = response.data as TLeaderboardData
Тип возвращает, но он TLeaderboardData | TAPIError, можно сузить тип, но так как вариант TAPIError отбрасывается в методе responseHasError, то тип точно является TLeaderboardData. Компилятор это не распознает, приходится указывать через as (как более короткая запись, чем если в лоб проверять тип)  Аналогично и с TUser.

2024-04-25 19:56 UTC, zhel1 commented on packages/client/src/store/leaderboardState.ts
> +  items: TLeaderboardData | undefined
Да, думаю лучше обозначить items как обязательное поле

2024-04-26 08:32 UTC, kate-lozovaya commented on packages/client/src/services/leaderboard.ts
> +  const list = response.data as TLeaderboardData
`TAPIError` должен быть отброшен после проверки, функция `responseHasError` возвращает тип `response is TResult<TAPIError>`, то есть вне `if` останется только `TResult<TLeaderboardData>` и его нужно правильно обработать, чтобы TS понял, что остается `TLeaderboardData`.
Возможно, в функции `leaderboardApi.getLeaderboard` неверно написан тип. Проверь его, пожалуйста

2024-04-26 08:40 UTC, kate-lozovaya reviewed
Оставила комментарий про типы. Код выглядит так, что там должна быть возможность не использовать `as`, потому что тип у функции определен и проверка на ошибку выполнена верно, она должна отсекать тип с ошибкой, то есть оставлять только нужный результат.

Проверь, пожалуйста, что в функции из апи тип прописан верно. 
Если это окажется чем-то сложным, и ничего не получится, не критично, не буду тебя блокировать, но хочется, чтобы код был с честным TS, который спасет от ошибок )

2024-04-26 08:40 UTC, kate-lozovaya commented on packages/client/src/services/leaderboard.ts
> +  const leaders = response.data as TLeaderboardData
[Дублирую комментарий из треда к прошлому ревью]
`TAPIError` должен быть отброшен после проверки, функция `responseHasError` возвращает тип `response is TResult<TAPIError>`, то есть вне `if` останется только `TResult<TLeaderboardData>` и его нужно правильно обработать, чтобы TS понял, что остается `TLeaderboardData`.
Возможно, в функции `leaderboardApi.getLeaderboard` неверно написан тип. Проверь его, пожалуйста

2024-04-27 08:47 UTC, kate-lozovaya approved these changes
👍🏻

2024-04-27 08:47 UTC, kate-lozovaya commented on packages/client/src/utils/http.ts
> +  body?: object
[Предложение]
Можно передавать значения в объекте, тогда не нужен будет `undefined` при вызове функций

2024-04-27 16:30 UTC, merged