Dre 31
harlequin-plus/dreamteam_mf05 pull request #5
Opened 2024-03-14 07:39 UTC by palhair

### Сверстана страница профиля. функции смены пароля, аватара

### ![image](https://github.com/harlequin-plus/dreamteam_mf05/assets/53209138/b2bd8c8f-e967-42fd-8e07-bf0505018a36)

2024-03-14 07:46 UTC, palhair commented
Частично скопировал Authapi и сервис у Михаила.

2024-03-14 08:58 UTC, harlequin-plus commented on packages/client/src/api/type.tsx
> +export type Chat = {
Эти типы нигде не используются.
Наверное все, что связано с чатом в этом проекте не пригодится. Лучше удалить для чистоты проекта

2024-03-14 09:10 UTC, harlequin-plus commented on packages/client/src/pages/Profile.tsx
> +        avatar={`https://ya-praktikum.tech/api/v2/resources${userInfo.avatar}`}
Можно тоже перенести в константы src/constants.tsx

2024-03-14 10:50 UTC, harlequin-plus approved these changes

2024-03-14 18:23 UTC, IvanPeleshok commented on packages/client/src/App.test.tsx
> +// @ts-ignoregit
Для какой цели заменили запись?

2024-03-14 18:39 UTC, IvanPeleshok requested changes
Отлично потрудились!
Есть пара замечаний и вопросов

Предлагаю доработать

Хорошего дня :)

2024-03-14 18:39 UTC, IvanPeleshok commented on packages/client/src/App.test.tsx
> +// @ts-ignoregit
Для какой цели заменили запись?

2024-03-14 18:39 UTC, IvanPeleshok commented on packages/client/src/api/authApi.tsx
> +    const getUser = await fetch(`${baseURL}/auth/user`, {
Предлагаю для запросов использовать axios https://www.npmjs.com/package/axios
Отлично подходит для работы с запросами, большой функционал
Для создания какой-то общей конфигурации отлично подойдёт axios.create https://axios-http.com/ru/docs/instance

Предлагаю переписать все запросы на axios или похожую обёртку для минимизации кода, а также переписать then / catch на try catch + async / await https://learn.javascript.ru/async-await

2024-03-14 18:39 UTC, IvanPeleshok commented on packages/client/src/components/BasicModal/index.tsx
> +  ] = useState({})
Предлагаю использовать дженерики, а не объявлять типы напрямую
```
useState<DataBasicModalForm>({})
```
Аналогично ниже

2024-03-14 18:39 UTC, IvanPeleshok commented on packages/client/src/components/BasicModal/index.tsx
> +            onSubmit={event => {
Инлайн колбеки с логикой выносим в функции 
```
const handleSubmit = (event: Type) => {

}

return (
 <Box onSubmit={handleSubmit}
 ```
 Проще читать и есть возможность оптимизаций
 
 Аналогичные кейсы предлагаю посмотреть соответственно в рамках MR

2024-03-14 18:39 UTC, IvanPeleshok commented on packages/client/src/components/BasicModal/index.tsx
> +const BasicModal: Props = ({ ...otherProps }) => {
BasicModal звучит, как базовая реализация, которая может быть переиспользована

Все элементы компоненты захардкожены, что не соответствует названию

Либо заменить название, либо реализовать компонент с переиспользуемым интерфейсом

2024-03-14 18:39 UTC, IvanPeleshok commented on packages/client/src/components/BasicModal/index.tsx
> +            {inputs.map(input => {
Есть ощущени, что данную логику лучше декомпозировать в отдельный модуль (компонент)

2024-03-14 18:39 UTC, IvanPeleshok commented on packages/client/src/components/ChangeAvatar/index.tsx
> +          onSubmit={event => {
Выносим

2024-03-14 18:39 UTC, IvanPeleshok commented on packages/client/src/components/ChangeAvatar/index.tsx
> +  ] = useState()
Типизируем через дженерик

2024-03-14 18:39 UTC, IvanPeleshok commented on packages/client/src/components/ChangeAvatar/index.tsx
> +                const files = (event.target as HTMLInputElement).files
Выносим, аналогично функции в других модулях

2024-03-14 18:39 UTC, IvanPeleshok commented on packages/client/src/constants.tsx
> +export const baseURL = 'https://ya-praktikum.tech/api/v2'
Супер, что вынесли в переменные :)

2024-03-14 18:39 UTC, IvanPeleshok commented on packages/client/src/pages/Profile.tsx
> +    getUser()
try / catch + async / await

Аналогичные моменты соответственно (then / catch желательно избегать)

2024-03-14 18:39 UTC, IvanPeleshok commented on packages/client/src/services/apiService.tsx
> +const getUser = async () => {
Для какой цели нужны обёртки для запросов?

2024-03-14 18:59 UTC, palhair commented on packages/client/src/App.test.tsx
> +// @ts-ignoregit
видимо хотел выполнить команду git и не посмотрел куда пишу =)

2024-03-18 19:08 UTC, IvanPeleshok requested changes
Добрый день!

Замечательно, что внедрили axios

Заметил, что не все замечания доработаны
Хотелось бы получить ответ на каждый комментарий, причину по которой решили не исправлять, либо поправить :)

Хорошего дня 🥇

2024-03-18 19:08 UTC, IvanPeleshok commented on packages/client/src/api/authApi.tsx
> +authAxios.defaults.withCredentials = true
Некоторые сущности повторяются в каждом модуле, к примеру packages/client/src/api/userApi.tsx

Рекомендация: вынести их в базовую реализацию `BaseApi` (как пример)

2024-03-19 04:24 UTC, palhair commented on packages/client/src/pages/Forum.tsx
Этот модуль из другой задачи, случайно в эту ветку попал

2024-03-19 04:24 UTC, palhair commented on packages/client/src/components/InputPassword/index.tsx
этот модуль больше не используется, удалю

2024-03-19 04:34 UTC, palhair commented on packages/client/src/api/authApi.tsx
> +authAxios.defaults.withCredentials = true
Базовая реализация должна добавить 2 параметра и baseUrl?

2024-03-19 04:39 UTC, palhair commented on packages/client/src/components/BasicModal/index.tsx
> +const BasicModal: Props = ({ ...otherProps }) => {
Поменял название на ModalForm, используется для создания формы в модальном окне, инпуты передаются в виде массива

2024-03-19 04:39 UTC, palhair commented on packages/client/src/components/BasicModal/index.tsx
> +            {inputs.map(input => {
вынес в отдельный модуль

2024-03-19 08:25 UTC, IvanPeleshok commented on packages/client/src/api/authApi.tsx
> +authAxios.defaults.withCredentials = true
Такое реализуют через наследование и прокидывание аргументов в конструктор родителя через super
```
class Base  {
  private baseURL;
  
  constructor (entry: string) {
    this.baseURL = BASE_URL + entry
  }
}

AuthApi extends BaseApi {
  constructor () {
    super('/auth')
  }
 }

2024-03-19 08:33 UTC, IvanPeleshok requested changes
Отлично порефакторили, нравится

Есть пара замечаний, который предлагаю доработать

Хорошего дня :)

2024-03-19 08:33 UTC, IvanPeleshok commented on packages/client/src/api/authApi.tsx
> +const baseApi = new BaseApi('/auth')
В комменте показал, как можно бы было реализовать через наследование
https://github.com/harlequin-plus/dreamteam_mf05/pull/5#discussion_r1529922970

2024-03-19 08:33 UTC, IvanPeleshok commented on packages/client/src/api/authApi.tsx
> +      ...reqData,
Для чего деструктуризация?

2024-03-19 08:33 UTC, IvanPeleshok commented on packages/client/src/api/baseApi.ts
> +  #baseUrl: string
В рамках ts пользуемся private / public / protected

2024-03-19 08:33 UTC, IvanPeleshok commented on packages/client/src/api/baseApi.ts
> +      if (error instanceof AxiosError && error.response?.data.reason) {
Обработку ошибки можно вынести в отдельный метод, чтобы не дублировать код

2024-03-19 08:33 UTC, IvanPeleshok commented on packages/client/src/components/ControlledInput/index.tsx
> +    // const onFocusHandler = (event: SyntheticEvent) => {
Если не используем - удаляем или оставляем содержательный комментарий для чего закомменчено

2024-03-19 08:33 UTC, IvanPeleshok commented on packages/client/src/components/ControlledInput/index.tsx
> +                  //   onMouseDown={handleMouseDownPassword}
Аналогично

2024-03-19 08:33 UTC, IvanPeleshok commented on packages/client/src/components/ControlledInput/index.tsx
> +ControlledInput.defaultProps = {
Нет никакой необходимости, можно выставить значение по умолчанию на момоменте деструктуризации в параметрах 
```
 ({ isPassword = false, type = 'text', name, label, autoComplete }: OwnProps
 ```
 В других местах аналогично

2024-03-19 08:33 UTC, IvanPeleshok commented on packages/client/src/components/ModalForm/index.tsx
> +ModalForm.defaultProps = {
Предлагаю везде избавиться от такого подхода и переписать на установку в параметрах

2024-03-19 09:44 UTC, palhair commented on packages/client/src/api/authApi.tsx
> +const baseApi = new BaseApi('/auth')
Моя реализация подойдет же?

2024-03-19 09:44 UTC, palhair commented
Вроде все поправил...

2024-03-19 16:40 UTC, IvanPeleshok approved these changes
Поздравляю, работа принята!

Хорошего дня :)

2024-03-19 16:40 UTC, IvanPeleshok commented on packages/client/src/api/authApi.tsx
> +const baseApi = new BaseApi('/auth')
Её сложно масштабировать, но для реализации подойдёт

Предлагаю записать в тех.долг доработку (она совсем небольшая)

2024-03-19 18:53 UTC, merged